[package]
name = "ruffer"
description = "A simple overwriting ring buffer library written in Rust."
version = "1.0.2"
edition = "2021"
license = "Apache-2.0"
authors = ["Chris Buchter"]
repository = "https://github.com/PrintPractical/ruffer"

[features]
sync = []

[dependencies]
